# Codecov 配置文件
# 用于配置代码覆盖率报告和检查

coverage:
  # 精度设置
  precision: 2
  # 舍入模式
  round: down
  # 范围设置
  range: 70...100

  # 状态检查配置
  status:
    # 项目级别检查
    project:
      default:
        # 目标覆盖率
        target: 85%
        # 允许的下降幅度
        threshold: 1%
        # 基准分支
        base: auto
        # 检查标志
        flags:
          - cache
        # 路径过滤
        paths:
          - packages/cache/src
    
    # 补丁级别检查
    patch:
      default:
        target: 80%
        threshold: 5%
        base: auto
        flags:
          - cache
        paths:
          - packages/cache/src

  # 忽略的路径
  ignore:
    - packages/cache/dist
    - packages/cache/lib
    - packages/cache/es
    - packages/cache/cjs
    - packages/cache/types
    - packages/cache/docs
    - packages/cache/examples
    - packages/cache/__tests__
    - packages/cache/coverage
    - "packages/cache/**/*.d.ts"
    - "packages/cache/**/*.config.*"
    - "packages/cache/**/*.test.*"
    - "packages/cache/**/*.spec.*"

# 标志配置
flags:
  cache:
    paths:
      - packages/cache/src
    carryforward: true

# 注释配置
comment:
  layout: "reach,diff,flags,tree"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes
  branches:
    - main
    - develop

# GitHub 检查配置
github_checks:
  annotations: true

# 解析器配置
parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no
