export * from './batch-helpers';
export * from './compressor';
export * from './error-handler';
export { EventEmitter } from './event-emitter';
export * from './event-throttle';
export * from './min-heap';
export * from './object-pool';
export * from './performance-profiler';
export * from './prefetcher';
export * from './retry-manager';
export * from './serialization-cache';
export * from './validator';
export declare function isBrowser(): boolean;
export declare function isNode(): boolean;
export declare function isWebWorker(): boolean;
export declare function isSSR(): boolean;
export declare function isValidInput(input: unknown): input is NonNullable<unknown>;
export declare function isEmpty(value: unknown): value is null | undefined | '';
export declare function isNonEmptyString(value: unknown): value is string;
export declare function safeJsonParse<T = unknown>(json: string, defaultValue: T): T;
export declare function safeJsonStringify(value: unknown, space?: number): string;
export declare function deepClone<T>(obj: T): T;
export declare function deepMerge<T extends Record<string, unknown>>(target: T, ...sources: Partial<T>[]): T;
export declare function once<T extends (...args: unknown[]) => unknown>(func: T): (...args: Parameters<T>) => ReturnType<T> | undefined;
export declare function formatBytes(bytes: number, decimals?: number): string;
export declare function formatNumber(num: number): string;
export declare function formatPercentage(value: number, decimals?: number): string;
export declare function generateId(prefix?: string): string;
export declare function generateUUID(): string;
export declare function delay(ms: number): Promise<void>;
export declare function withTimeout<T>(promise: Promise<T>, timeoutMs: number, timeoutMessage?: string): Promise<T>;
export declare function clamp(value: number, min: number, max: number): number;
export declare function randomInt(min: number, max: number): number;
//# sourceMappingURL=index.d.ts.map